name: New Release

on:
    push:
        tags:
            - '*'

env:
    CARGO_TERM_COLOR: always

jobs:
    upload-release:
        runs-on: ubuntu-latest
        needs: [build-linux, build-windows, macos-linux]

        steps:
            - uses: actions/checkout@v2

            - name: download artifacts
              uses: actions/download-artifact@v1
              with:
                  name: uploads
            - name: Get Changelog Entry
              id: changelog_reader
              uses: mindsers/changelog-reader-action@v2
              with:
                  validation_depth: 10
                  version: ${{ steps.tag_name.outputs.current_version }}
                  path: ./CHANGELOG.md

            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: |
                      uploads/tpy.exe
                      uploads/tpy
                      uploads/tpy-macos
                  token: ${{ secrets.GITHUB_TOKEN }}
                  body: ${{ steps.changelog_reader.outputs.changes }}

    build-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build for linux
              run: cargo build --release

            - name: Rename binary
              run: mv target/release/templify tpy

            - name: upload linux artifact
              uses: actions/upload-artifact@v1
              with:
                  name: uploads
                  path: tpy

    macos-linux:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build for linux
              run: cargo build --release

            - name: Rename binary
              run: mv target/release/templify tpy

            - name: upload linux artifact
              uses: actions/upload-artifact@v1
              with:
                  name: uploads
                  path: tpy-macos

    build-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build for windows
              run: cargo build --release

            - name: Rename binary
              run: mv target/release/templify.exe tpy.exe

            - name: upload linux artifact
              uses: actions/upload-artifact@v1
              with:
                  name: uploads
                  path: tpy.exe
